version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
        # No need for depends_on since we're using remote databases
    # No need for networks since we're connecting to external services 