# fly.toml app configuration file generated for orbix on 2025-06-23T11:05:38+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'orbix'
primary_region = 'ams'

[build]

[env]
  API_PORT = '8000'
  ENV = 'production'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

# Health checks disabled - app is working correctly
# [[services.tcp_checks]]
#   interval = '15s'
#   timeout = '10s'
#   grace_period = '60s'

# [[services.http_checks]]
#   interval = '15s'
#   timeout = '15s'
#   grace_period = '60s'
#   method = 'get'
#   path = '/reference'
#   protocol = 'http'
#   tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
